# Generated by Django 4.2.19 on 2025-04-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
    ]
