# Generated by Django 4.2.19 on 2025-04-20 01:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

def remove_duplicate_ratings(apps, schema_editor):
    Rating = apps.get_model('api', 'Rating')
    Rating.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_is_featured'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_ratings),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.project'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('project', 'user')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='technical_skills',
        ),
    ]
