# Generated by Django 4.2.19 on 2025-04-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_feedback_project_reportedfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
